"""
Reads _data/tools/*.yml, queries the GitHub API for each tool with a
`github: owner/repo` field, and writes health metadata to _data/health.yml.

Status classification:
  active     — last commit within 6 months
  maintained — last commit within 2 years
  quiet      — last commit within 5 years
  dormant    — last commit older than 5 years
  archived   — repository is archived on GitHub
"""

import os
import glob
import yaml
import requests
from datetime import datetime, timezone, timedelta

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
HEADERS = {"Authorization": f"Bearer {GITHUB_TOKEN}"} if GITHUB_TOKEN else {}
API = "https://api.github.com/repos/{}"

NOW = datetime.now(timezone.utc)
THRESHOLDS = {
    "active":     timedelta(days=180),
    "maintained": timedelta(days=730),
    "quiet":      timedelta(days=1825),
}


def classify(last_push: datetime, is_archived: bool) -> str:
    if is_archived:
        return "archived"
    age = NOW - last_push
    for status, threshold in THRESHOLDS.items():
        if age <= threshold:
            return status
    return "dormant"


def check_repo(github_slug: str) -> dict:
    r = requests.get(API.format(github_slug), headers=HEADERS, timeout=10)
    r.raise_for_status()
    data = r.json()
    last_push = datetime.fromisoformat(data["pushed_at"].replace("Z", "+00:00"))
    return {
        "stars": data["stargazers_count"],
        "last_commit": last_push.strftime("%Y-%m-%d"),
        "status": classify(last_push, data["archived"]),
        "checked_at": NOW.strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def main():
    health = {}
    tool_files = glob.glob("_data/tools/*.yml")

    for path in tool_files:
        with open(path) as f:
            tools = yaml.safe_load(f) or []
        for tool in tools:
            slug = tool.get("github")
            if not slug:
                continue
            key = slug.replace("/", "-")
            try:
                health[key] = check_repo(slug)
                print(f"  {slug}: {health[key]['status']}")
            except Exception as e:
                print(f"  {slug}: error — {e}")

    with open("_data/health.yml", "w") as f:
        f.write("# Auto-generated by scripts/update_health.py — do not edit by hand.\n")
        yaml.dump(health, f, default_flow_style=False, allow_unicode=True)


if __name__ == "__main__":
    main()
